### ISSUE TITLE
Missing command in README

### ISSUE THREAD

**Issue by syrm** [timatooth/gofit#2]
Hello,

You should add these command in README : 
go get github.com/influxdata/influxdb/client/v2
go get github.com/timatooth/gofit/fitbitapi

**Comment by timatooth** [comment]
Thanks for pointing that out. I think I have found a single command that will do the trick to install gofit + any dependencies: 

https://github.com/timatooth/gofit/commit/5b028907a099deab9787826cdebe62fdeab5c253
